wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.get_entry,name="get_entry"),
    path("random",views.random_entry,name='random_entry'),
    path("search",views.search,name="search"),
    path("new_page",views.create_new_page,name="new_page"),
    path("edit/<str:title>",views.edit_page,name='edit_page')
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import random
import markdown2
from . import util
from django.contrib import messages

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def get_entry(request,title):


    entry=util.get_entry(title)
    if entry:

        entry=markdown2.markdown(f"{entry}")
        return render(request,"encyclopedia/get_entry.html",{
            "title": title,
            "entry": entry,
        })
    else:
        return render(request,"encyclopedia/error.html")


def random_entry(request):
    all_entries=util.list_entries()
    random_title=random.choice(all_entries)
    return HttpResponseRedirect(reverse("wiki:get_entry",args=(random_title,)))


def search(request):
    if request.method == 'GET':
        query=request.GET['q']
        if query.lower() in [old.lower() for old in util.list_entries()]:
            return HttpResponseRedirect(reverse("wiki:get_entry", args=(query,)))
        else:
            list_of_entries = []
            for entry in util.list_entries():
                if query.lower() in entry.lower():
                    list_of_entries.append(entry)

            return render(request,"encyclopedia/search.html",{
                "list": list_of_entries,
            })


def create_new_page(request):
    if request.method == 'POST':
        title=request.POST.get('title')
        content = request.POST.get('content')
        if not title.lower() in [old.lower() for old in util.list_entries()]:
            with open(f"entries/{title}.md","w") as new_entry:
                new_entry.write(content)
            return HttpResponseRedirect(reverse("wiki:get_entry", args=(title,)))
        else:
            # messages.add_message(request, messages.error, "Hello world.")
            messages.error(request, "Entry already exist")
    return render(request,"encyclopedia/new_page.html")


def edit_page(request,title):
    if request.method == 'POST':
        new_body=request.POST.get("body")
        util.save_entry(title,new_body)
        return HttpResponseRedirect(reverse("wiki:get_entry",args=(title,)))
    body = util.get_entry(title)
    return render(request,"encyclopedia/edit_page.html",{
        "title": title,
        "body": body,
    })

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}Edit{% endblock %}
{% block body %}
<h1>{{title}}</h1>

<form action="{% url 'wiki:edit_page' title=title %}" method="POST">
  {% csrf_token %}
  <textarea name="body">{{body}}</textarea><br>
  <input type="submit">
</form>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends 'encyclopedia/layout.html' %}


{% block title %}Error{% endblock %}

{% block body %}
<h1>Requested page was not found</h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/get_entry.html
{% extends 'encyclopedia/layout.html' %}


{% block title %}{{title}}{% endblock %}

{% block body %}
{% if entry %}
{{entry|safe}}
<a href="{% url 'wiki:edit_page' title=title %}" class="edit">Edit entry</a>
{% else %}
<h1>Oops! We are having trouble finding your page.</h1>
<h2>There is no entry for this query</h2>

{% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'wiki:get_entry' title=entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">Create New Page<a/>
                </div>
                <div>
                    <a href="{% url 'wiki:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends 'encyclopedia/layout.html' %}


{% block title %}New Page{% endblock %}

{% block body %}


<form action="{% url 'wiki:new_page' %}" method="POST">
  {% csrf_token %}

  <label>Enter the title:</label><br>
  <input type="text" name="title" placeholder="bla bla"><br>
     {% if messages %}
        <ul class="messages_error">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  <label>Enter the Markdown content for the page:</label><br>
  <textarea id="story" name="content">
It was a dark and stormy night...
</textarea><br>
  <input type="submit">


</form>

{% endblock %}


wiki/encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search Bar
{% endblock %}


{% block body %}
  {% if list %}
  <h1>Results for your query:</h1>
    <ul>

    {% for entry in list %}
      <a href="{% url 'wiki:get_entry' title=entry%}" ><li>{{entry}}</li></a>
    {% endfor %}
     {% else %}
      <h2 id="bad_query">There is no any entry with this name</h2>
      {% endif %}
    </ul>

{% endblock %}